### ISSUE TITLE
uninitialized constant Sinatra::Sprockets::Closure

### ISSUE THREAD

**Issue by brandonweiss** [thegorgon/sinatra-sprockets#1]
I'm on the latest version of everything, but I can't seem to configure it; I get a boot error: uninitialized constant Sinatra::Sprockets::Closure.

**Comment by thegorgon** [comment]
Probably missing the closure gem. Are you using bundler? If not, be sure to install closure-compiler

**Comment by brandonweiss** [comment]
I am using bundler, and closure-compiler is being installed. But it's failing in the `Sinatra::Sprockets.configure` block when I try to set `config.app` to my app. Any idea what might be wrong?

**Comment by adambair** [comment]
I ran into this as well.

**Comment by thegorgon** [comment]
Can one of you provide your configuration setup? I might be able to help if I can see your code.

**Comment by johnnym** [comment]
I also ran into this. Here's a sample application.

https://gist.github.com/1463739

**Comment by kyledrake** [comment]
I have a pull request that fixes this problem: https://github.com/thegorgon/sinatra-sprockets/pull/2

We have pushed a geoloqi-sinatra-sprockets gem as a workaround until the sinatra-sprockets 0.0.3 gem is pushed: http://rubygems.org/gems/geoloqi-sinatra-sprockets

**Comment by dcalhoun** [comment]
Has this issue been resolved? I'm still seeing this with the 0.1.1 version of this [gem](http://rubygems.org/gems/alphasights-sinatra-sprockets). I have an identical setup to @johnnym.
